source 'http://rubygems.org'

gem 'mecab-ruby', git: 'git://github.com/eitoball/mecab-ruby.git'
gem 'thor', '~> 0.14.6'
gem 'twitter', '~> 2.0.2'
gem 'userstream', '~> 1.0.0'
gem 'mongo', '~> 1.5.2'
gem 'bson_ext', '~> 1.5.2'
gem 'activesupport', '~> 3.1.3', require: 'active_support/core_ext'
gem 'i18n', '~> 0.6.0'
